export const ErrorCode = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  OUT_OF_SCOPE: 'OUT_OF_SCOPE',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_ACCOUNT_DISABLED: 'AUTH_ACCOUNT_DISABLED',
  AUTH_RATE_LIMITED: 'AUTH_RATE_LIMITED',
  SALARY_ALREADY_LOCKED: 'SALARY_ALREADY_LOCKED',
  SALARY_NOT_READY_FOR_APPROVAL: 'SALARY_NOT_READY_FOR_APPROVAL',
  SALARY_REVISION_REQUIRED: 'SALARY_REVISION_REQUIRED',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
