/**
 * Nhật ký chỉ lưu các thay đổi nghiệp vụ nhạy cảm cần truy vết lâu dài.
 * Notification của KPI/OKR vẫn được phát riêng, nhưng không tạo audit log.
 */
export const AUDITED_ACTIONS = [
  'USER_CREATED',
  'USER_UPDATED',
  'USER_ROLES_UPDATED',
  'ROLE_CREATED',
  'ROLE_UPDATED',
  'ROLE_PERMISSIONS_UPDATED',
  'EMPLOYEE_CREATED',
  'EMPLOYEE_UPDATED',
  'PAYROLL_PERIOD_CREATED',
  'PAYROLL_PERIOD_UPDATED',
  'PAYROLL_PERIOD_OPENED',
  'PAYROLL_PERIOD_SNAPSHOTS_SYNCED',
  'PAYROLL_PERIOD_START_REVIEW',
  'PAYROLL_PERIOD_CLOSED',
  'BASE_SALARY_HISTORY_CREATED',
  'BASE_SALARY_HISTORY_UPDATED',
  'KPI_REWARD_RATE_CREATED',
  'KPI_REWARD_RATE_UPDATED',
  'KPI_REWARD_RATE_DELETED',
  'REWARD_RULE_SET_CREATED',
  'REWARD_RULE_SET_ACTIVATED',
  'REWARD_RULE_SET_ARCHIVED',
  'REVENUE_REWARD_BRACKET_CREATED',
  'REVENUE_REWARD_BRACKET_UPDATED',
  'REVENUE_REWARD_BRACKET_DELETED',
  'SALARY_CALCULATED',
  'SALARY_RECALCULATED',
  'SALARY_APPROVED',
  'SALARY_LOCKED',
  'SALARY_REVISION_CREATED',
  'SALARY_BONUS_ADDED',
  'SALARY_BONUS_REMOVED',
  'REVENUE_CREATED',
  'REVENUE_UPDATED',
  'TRAFFIC_CREATED',
  'TRAFFIC_UPDATED',
  // Traffic đồng bộ từ AutomationGenVideo cũng vào thẳng công thức lương như số nhập tay, nên
  // phải truy vết được y như TRAFFIC_CREATED/TRAFFIC_UPDATED.
  'TRAFFIC_SYNCED',
  'KPI_ACTUAL_OVERRIDE',
  'OKR_ACTUAL_OVERRIDE',
] as const;

const auditedActionSet = new Set<string>(AUDITED_ACTIONS);

export function isAuditedAction(action: string) {
  return auditedActionSet.has(action);
}
